#pragma once

#ifndef HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#    define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#endif

#ifndef PERMISSIVE_HOLD_PER_KEY
#    define PERMISSIVE_HOLD_PER_KEY
#endif

#ifndef RETRO_TAPPING_PER_KEY
#    define RETRO_TAPPING_PER_KEY
#endif

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 9
#define AUTO_MOUSE_TIME 650
